### ISSUE TITLE
I made this mistake when I repeated your experiment，i don't know why,can you tell me?thank you  

### ISSUE THREAD

**Issue by YI52KE** [x4nth055/pythoncode-tutorials#10]
![image](https://user-images.githubusercontent.com/51817054/76084457-e3611d80-5fea-11ea-88fd-e2137e7303fc.png)

**Comment by x4nth055** [comment]
Hello,

Can you provide more information ? on what tutorial is this ?
Also, can you please copy the whole error traceback ? along with your system info.

Thanks.

**Comment by YI52KE** [comment]
This tutorial is speech -emotion - recongion,my system si win10+python3.6(pycharm),Error when running to ser。

**Comment by YI52KE** [comment]
![捕获](https://user-images.githubusercontent.com/51817054/76086788-c8dd7300-5fef-11ea-8170-adc51fd12354.PNG)
This is the result of the run display

**Comment by x4nth055** [comment]
If you're using your own audio samples, you should convert them to monophonic channel and 16000 sample rate using utilities like ffmpeg.

You can follow along with the tutorial here: 
https://www.thepythoncode.com/article/building-a-speech-emotion-recognizer-using-sklearn

**Comment by YI52KE** [comment]
i use RAVDESS database.Does it also need to modify the sampling rate?

**Comment by YI52KE** [comment]
Thank you very much .I saved this problem
