### ISSUE TITLE
Pytorch code

### ISSUE THREAD

**Issue by nigelhiggs** [x4nth055/pythoncode-tutorials#11]
I'm trying to implement the Pytorch code to extract the bounding boxes cordinates for (pseudo labeling). I'm printing the "boxes" variable and getting this output 
`[[tensor(0.4833), tensor(0.5783), tensor(0.4487), tensor(0.5920), tensor(0.9858), tensor(0.9875), tensor(1)]]`
I'm confused as to the set up of the output i'm assuming it's (x, y, w, h, ?, ?, number_of_detected_imgs)
clarity would be appreciated thanks!

**Comment by x4nth055** [comment]
Hello,

I'm not the owner of the code, but each object detection shape is (x, y, w, h, ?, confidence, the class id of the object detected).

I'm not sure about that 5th tensor, if you find out what it is, you can comment here.

Thanks,
Rockikz
