### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by moonface19** [x4nth055/pythoncode-tutorials#12]
The error that has occurred is:
```
X_train.shape: (4181, 100)
X_test.shape: (1394, 100)
y_train.shape: (4181,)
y_test.shape: (1394,)
Train on 4181 samples, validate on 1394 samples
Epoch 1/20
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-cef5243aa57c> in <module>
     15           batch_size=BATCH_SIZE, epochs=EPOCHS,
     16           callbacks=[tensorboard, model_checkpoint],
---> 17           verbose=1)

~\Anaconda3\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1037                                         initial_epoch=initial_epoch,
   1038                                         steps_per_epoch=steps_per_epoch,
-> 1039                                         validation_steps=validation_steps)
   1040 
   1041     def evaluate(self, x=None, y=None,

~\Anaconda3\lib\site-packages\keras\engine\training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    197                     ins_batch[i] = ins_batch[i].toarray()
    198 
--> 199                 outs = f(ins_batch)
    200                 outs = to_list(outs)
    201                 for l, o in zip(out_labels, outs):

~\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

~\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in _call(self, inputs)
   2653                 array_vals.append(
   2654                     np.asarray(value,
-> 2655                                dtype=tf.as_dtype(tensor.dtype).as_numpy_dtype))
   2656         if self.feed_dict:
   2657             for key in sorted(self.feed_dict.keys()):

~\Anaconda3\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)
    536 
    537     """
--> 538     return array(a, dtype, copy=False, order=order)
    539 
    540 

ValueError: could not convert string to float: 'ham,Ok'
```
```

Please help me with this.Thanks.

**Comment by x4nth055** [comment]
Hello,

I would like to know which tutorial's code is this ?

Thanks,
Rockikz.

**Comment by thecoder19** [comment]
> Hello,
> 
> I would like to know which tutorial's code is this ?
> 
> Thanks,
> Rockikz.

This code is from the spam-classifier using keras by pythoncode tutorials.
Here's the link to it https://www.thepythoncode.com/code/build-spam-classifier-keras-python

**Comment by x4nth055** [comment]
Hello @moonface19 ,

I know it's been a while. The tutorial is updated now with the latest TF versions. and now similar issues won't hopefully happen.

Thanks!
