### ISSUE TITLE
...not recognized as an internal or external command

### ISSUE THREAD

**Issue by D1dymu2** [x4nth055/pythoncode-tutorials#13]
Hi x$nth055,

Excellent code, thank you.
My system:
    O/S: Win10
    Python: 3.6.2
    Firefox: 74.-(64-bit)
    (do you need another information?)

target download site: 
https://www.silky-europe.com/alle-producten?SID=dd9f2ff67051f25c98a7f7f98cc25ed6&limit=12&p=4

Your code was "cut&paste" to text editor so nothing changed in code.

command used to download:  
python download_images.py https://www.silky-europe.com/alle-producten?SID=dd9f2ff67051f25c98a7f7f98cc25ed6&limit=12&p=4

result:  images downloaded and folder created as expected.  I am not too sure if entire compliment of web page images were downloaded.

error:  'limit' is not recognized as an internal or external command, operable program or batch file.
           'p' is not recognized as an internal or external command, operable program or batch file.

Can you advise please?  Is there something that I should be looking for in the error message?

Stay safe and well,
Tommy.

**Comment by x4nth055** [comment]
Hello Tommy,

Thanks for your support,

I would like to tell you that the command line (I think both on Windows & Linux) parses & as a special character and has its functionalities, as a result, you should try to wrap the url with double quotes, something like this:
`python download_images.py "https://www.silky-europe.com/alle-producten?SID=dd9f2ff67051f25c98a7f7f98cc25ed6&limit=12&p=4"`

Additionally, if the website uses Javascript to load images, consider using `download_images_js.py` script instead. (which requires `requests_html` library installed)

Good luck on that task ! Please confirm if this solved your issue.

Regards,
Rockikz.
