### ISSUE TITLE
Not working with all websites

### ISSUE THREAD

**Issue by Monkiky** [x4nth055/pythoncode-tutorials#19]
Hi x4nth055, 

First, many thanks for your code and your altruism.

I am bioinformatics, not informatics so my knowledge about coding is quite limited. Sorry if the question is stupid.

I using your code to have fun and I try to get all links contained in the website https://es.quora.com/profile/Manolo-Dominguez-Becerra

Here I show you input and output

(base) Monkikys-MBP:Programming monkiky$ python link_extractor.py https://es.quora.com/profile/Manolo-Dominguez-Becerra -m 2
 

[+] Total Internal links: 0
[+] Total External links: 0
[+] Total URLs: 0

Your code worked with other websites but not with this. Do you know the reason?

Thanks in advances 

M

**Comment by x4nth055** [comment]
Hello Monkiky,

Thanks for pointing out, I updated the tutorial.

There are some websites that load most of its content using Javascript, as a result, we need to use requests_html library instead that enable us to execute Javascript using Chromium (Chrome browser driver), I already wrote a script for that by adding just few lines (as requests_html is quite similar to requests), check it [here](https://www.thepythoncode.com/code/extract-all-website-links-python#link_extractor_js).

Thanks.
