### ISSUE TITLE
NoneType Object Not Iterable

### ISSUE THREAD

**Issue by HardikTilwani** [x4nth055/pythoncode-tutorials#31]
Traceback (most recent call last):
  File "C:\Users\abc\PycharmProjects\Project1\venv\Scripts\new.py", line 60, in <module>
    data = get_video_info(url)
  File "C:\Users\abc\PycharmProjects\Project1\venv\Scripts\new.py", line 34, in get_video_info
    result["likes"] = int(''.join([c for c in text_yt_formatted_strings[0].attrs.get("aria-label") if c.isdigit()]))
TypeError: 'NoneType' object is not iterable

I am trying this script on a video where like and dislike are hidden, so how to retrieve it in this scenario - Help If Possible

**Comment by HardikTilwani** [comment]
Sorry Error Got Resolved By Adding

 result["likes"] = text_yt_formatted_strings[0].int
    # number of dislikes
    result["dislikes"] = text_yt_formatted_strings[1].int

But Still I Got Value of like and dislike as None - As they are hidden so how to retrieve it even if they are hidden

**Comment by x4nth055** [comment]
Hey there,
If it's hidden, I don't think there is a way to extract it, thanks for pointing out the error and I'll fix it soon.
Thanks!

**Comment by HardikTilwani** [comment]
No Problem - This Was Helpful Anyway - Thank You
