### ISSUE TITLE
can't detect all faces inside one picture which contain multi people.

### ISSUE THREAD

**Issue by wingxyq** [x4nth055/pythoncode-tutorials#40]
can't detect all faces inside one picture which contain multi people. i am wondering why? the photos faces are clear.

**Comment by x4nth055** [comment]
Hey @wingxyq ,

Can you tell me which script you're using ? Also, can you send the image so I can reproduce the issue, in order to work on it.

Thanks,

**Comment by wingxyq** [comment]
thanks very much and sorry. I am a very new beginner on python. now i have
never used this function for my work again. Thanks !!

**Comment by x4nth055** [comment]
Alright!
