### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by b24** [x4nth055/pythoncode-tutorials#43]
Am recieving the following SyntaxError when running the code:

> File "weather.py", line 62
> URL += f"+(region)"
>                                ^
> SyntaxError: invalid syntax

Looking at the code, the issue appears to be in this part:

if region:
       region = region.replace(" ", "+")
        URL += f"+{region}"

Troubleshooting now, interested to hear if anyone has a fix or has had this problem before.

**Comment by x4nth055** [comment]
Hi @b24,

Make sure you respect the Python indentations, and also use Python 3.6+ to support format string.

Please let me know if this solves your issue.

Thanks,
