### ISSUE TITLE
Live Barcode Reader high level newb question

### ISSUE THREAD

**Issue by ScotterMonk** [x4nth055/pythoncode-tutorials#46]
Hi -
May I assume the live barcode reader will run on a phone and be able to access the phone's camera? At a high level, how does that work? I have basic Python knowledge where I've built one web-based database-driven inventory management system and one simple 2D game but nothing more, really. So be gentle with me, heh.
Sincerely,
Scott Swain

**Comment by x4nth055** [comment]
Hey Scott,

Unfortunately, Python cannot run on a Android/Apple phone, the barcode reader will only work on platforms such as Windows, MacOS and Linux.

Hope this helps,
Thanks,
