### ISSUE TITLE
Link Extractor 

### ISSUE THREAD

**Issue by fiorins** [x4nth055/pythoncode-tutorials#53]
Hi, I don't understand what does it mean that it extract all links from 2 first URLs appeared in github.com, what are these 2 first URLs ?

**Comment by x4nth055** [comment]
Hello @fiorins ,

Sorry for the late response. The code in the link extractor gets the number of links you specify, the links that appear first in the HTML are extracted first.

Thanks,

**Comment by ommadiyar** [comment]
can i put url inside the code? please reply
