### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by pasha-bolokhov** [x4nth055/pythoncode-tutorials#62]
https://github.com/x4nth055/pythoncode-tutorials/blob/ed6d8faccd6f598065611564f360396cda0d978a/general/gmail-api/read_emails.py#L69
`msg` is not defined in that context

**Comment by x4nth055** [comment]
Hey @pasha-bolokhov ,

Thanks for pointing out, even though it was working (it was referencing a global variable), but it's worth fixing to reference a local variable instead, closing the issue.

Thanks,
